#1 - sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError)
 (2003, "Can't connect to MySQL server on '127.0.0.1' (61)")
	Fix: Make sure to use the same Port as MySQL and MySQL Workbench
#2 - sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError)
 (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
	Fix: Use the correct password "root" not "roots"
#3 - sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError)
 (1045, "Access denied for user 'roots'@'localhost' (using password: YES)") 
	Fix: Use the correct User name
#4 - sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError)
 (1049, "Unknown database 'mydbc'")
	Fix: Point to the proper db in the server.py file
